name: CI/CD - Weather API (Prod)

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - Dockerfile
      - .github/workflows/deploy-prod.yml

env:
  IMAGE_NAME: weather-api

jobs:
  build-and-push:
    name: Build & Push to ECR (Prod)
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      id: aws-creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify Caller Identity
      run: aws sts get-caller-identity

    - name: Login to Amazon ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to EC2 (Prod)
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: prod

    steps:
    - name: Deploy over SSH to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin $IMAGE
          docker stop weather-api || true && docker rm weather-api || true
          docker pull $IMAGE:latest
          docker run -d -p 8000:8000 --name weather-api \
            -e API_KEY=${{ secrets.API_KEY }} \
            $IMAGE:latest
