name: CI/CD - Weather API Multi-Env

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.py'
      - Dockerfile
      - .github/workflows/deploy.yml

env:
  IMAGE_NAME: weather-api

jobs:
  build-and-push-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Build & Push to Dev ECR
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
             docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

  build-and-push-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build & Push to Prod ECR
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
             docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

  deploy-dev:
    needs: build-and-push-dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Deploy to Dev EC2
    environment: dev
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/weather-api
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin $IMAGE
            docker stop weather-api || true && docker rm weather-api || true
            docker pull $IMAGE:latest
            docker run -d -p 8000:8000 --name weather-api \
              -e API_KEY=${{ secrets.API_KEY }} \
              $IMAGE:latest

  deploy-prod:
    needs: build-and-push-prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to Prod EC2
    environment: prod
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/weather-api
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin $IMAGE
            docker stop weather-api || true && docker rm weather-api || true
            docker pull $IMAGE:latest
            docker run -d -p 8000:8000 --name weather-api \
              -e API_KEY=${{ secrets.API_KEY }} \
              $IMAGE:latest
